Numpy array attributes and Properties.

In [2]:
import numpy as np
import pandas as pd
arr1=np.array([1,2,3,4,5])


In [8]:
arr1

array([1, 2, 3, 4, 5])

In [9]:
arr1.shape

(5,)

In [16]:
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [17]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [18]:
arr2.shape

(2, 5)

In [24]:
arr9=np.array([[1,2],[3,4],[5,6],[7,8]])

In [25]:
arr9.shape

(4, 2)

In [26]:
# Array 2  is a 2 dimensional matrix
arr2.ndim

2

In [28]:
arr1.ndim

1

In [3]:
arr7=np.linspace(10,20,10)


In [4]:
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [5]:
print(arr7)

[10.         11.11111111 12.22222222 13.33333333 14.44444444 15.55555556
 16.66666667 17.77777778 18.88888889 20.        ]


In [6]:
arr8=arr7.copy()

In [7]:
print(arr8)

[10.         11.11111111 12.22222222 13.33333333 14.44444444 15.55555556
 16.66666667 17.77777778 18.88888889 20.        ]


In [8]:
arr8.itemsize

8

In [10]:
arr9=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [11]:
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [14]:
arr9.dtype

dtype('int32')

In [15]:
arr9.astype('float')

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])