Creating N-D Array

In [3]:
import numpy as np
arr1=np.array([1,2,3,4,5])

In [5]:
# creating a 1-D array
arr1=np.array([1,2,3,4,5])

In [6]:
arr1

array([1, 2, 3, 4, 5])

In [9]:
type(arr1)

numpy.ndarray

In [14]:
# Creating a 2-D array
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [16]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
arr4=np.zeros((3,4))

In [19]:
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
arr5=np.ones((3,3))

In [23]:
arr5

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
arr6=np.arange(5,16,2)#This will return numpy array from 5 to 15

In [26]:
arr6

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [29]:
arr7=np.linspace(10,20,10)

In [31]:
arr8=arr7.copy()
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [4]:
arr1.size

5

NameError: name 'arr9' is not defined